insert into User (admin, email, pass, saldo, usuario) values (true, 'admin@admin.com', '$2a$10$WlXiUTynUF0DjDoF7CBx.ONTxKLdDUHE2cc9WnH4QSdCTF.djsJQ6', 100, 'admin')
insert into User (admin, email, pass, saldo, usuario) values (false, 'usuario@usuario.com', '$2a$10$lVMsEorscm0Kj65rw9toveisPAuEMee4QDV3ObZv/GgzBmBcXdGo.', 0, 'usuario')
insert into Product (almacenamiento, anchoBanda, disabled, mensualidad, tipo, type) values (15, 1000, false, 1, 'Básico', 'Hosting')
insert into Hosting (db, dominio, email, ftp, id) values (1, 1, 1, 1, 1)
insert into Product (almacenamiento, anchoBanda, disabled, mensualidad, tipo, type) values (25, 1000, false, 2, 'Básico', 'Server')
insert into Server (cpu, capacidadram, velocidadred, ssd, id) values (2, 1, 50, false, 2)
insert into Product (almacenamiento, anchoBanda, disabled, mensualidad, tipo, type) values (40, 2000, false, 5, 'Avanzado', 'Hosting')
insert into Hosting (db, dominio, email, ftp, id) values (5, 2, 10, 10, 3)
insert into Product (almacenamiento, anchoBanda, disabled, mensualidad, tipo, type) values (75, 2000, false, 9, 'Avanzado', 'Server')
insert into Server (cpu, capacidadram, velocidadred, ssd, id) values (8, 4, 100, false, 4)
insert into Product (almacenamiento, anchoBanda, disabled, mensualidad, tipo, type) values (100, 4000, false, 12, 'Premium', 'Hosting')
insert into Hosting (db, dominio, email, ftp, id) values (10, 25, 30, 30, 5)
insert into Product (almacenamiento, anchoBanda, disabled, mensualidad, tipo, type) values (500, 5000, false, 25, 'Premium', 'Server')
insert into Server (cpu, capacidadram, velocidadred, ssd, id) values (24, 12, 300, true, 6)
insert into Product (almacenamiento, anchoBanda, disabled, mensualidad, tipo, type) values (500, 10000, false, 35, 'Empresarial', 'Hosting')
insert into Hosting (db, dominio, email, ftp, id) values (10, 25, 30, 30, 7)
insert into Product (almacenamiento, anchoBanda, disabled, mensualidad, tipo, type) values (2000, 15000, false, 90, 'Empresarial', 'Server')
insert into Server (cpu, capacidadram, velocidadred, ssd, id) values (36, 32, 1000, true, 8)

