drop table Hosting if exists
drop table Orders if exists
drop table Product if exists
drop table Server if exists
drop table User if exists
drop table User_orders if exists

create table Hosting (db integer not null, dominio integer not null, email integer not null, ftp integer not null, id bigint not null, primary key (id))
create table Orders (id bigint generated by default as identity, fechaCaducidad date, fechaContratacion date, nombre varchar(255), producto_id bigint, usuario_id bigint, primary key (id))
create table Product (type varchar(31) not null, id bigint generated by default as identity, almacenamiento integer not null, anchoBanda integer not null, disabled boolean not null, mensualidad double not null, tipo varchar(255), primary key (id))
create table Server (capacidadRam integer not null, cpu integer not null, ssd boolean not null, velocidadRed integer not null, id bigint not null, primary key (id))
create table User (id bigint generated by default as identity, admin boolean not null, email varchar(255), pass varchar(255), saldo double not null, usuario varchar(255), primary key (id))
create table User_orders (User_id bigint not null, orders_id bigint not null, primary key (User_id, orders_id))
alter table User_orders add constraint UK_cvdypc9s7ikx9kpbqlo0vu4p4 unique (orders_id)
alter table Hosting add constraint FKk02ywegb2l5ri7a8l77fkwa9h foreign key (id) references Product
alter table Orders add constraint FKgdwuyplrds6wbl7qfsd9c80f0 foreign key (producto_id) references Product
alter table Orders add constraint FKr4e0oje784h7ce6cimle1du0a foreign key (usuario_id) references User
alter table Server add constraint FKd3rvw0k6itpenw3oidwgt4gce foreign key (id) references Product
alter table User_orders add constraint FKpfud3qstunq8ggqw24rrt21rv foreign key (orders_id) references Orders
alter table User_orders add constraint FKa77ot2dxiyndf1eu2qq9ulx04 foreign key (User_id) references User